#define AP_SSID "iotdevice"
#define AP_USE_PWD FALSE
#define AP_PWD "1234"
#define PORT 5000
#define DEBUG TRUE
#define CONN_RETRIES 3
#define AP_DEVICE_NAME "config"
#define ST_DEVICE_NAME "iotnew"
#define ST_CONN_TIMEOUT 10000
