#define AP_SSID "firefly"
#define AP_USE_PWD FALSE
#define AP_PWD "1234"
#define PORT 5000
#define DEBUG TRUE
#define CONN_RETRIES 3
#define AP_DEVICE_NAME "config"
#define ST_DEVICE_NAME "firefly"
#define ST_CONN_TIMEOUT 10000
#define ST_ANNOUNCE_PORT 3001
#define MDNS_DEBUG_RX TRUE
#define EEPROM_SIZE 512
