#define AP_SSID "firefly_"
#define AP_USE_PWD FALSE
#define AP_PWD "1234"
#define PORT 5000
#define DEBUG TRUE
#define CONN_RETRIES 3
#define AP_DEVICE_NAME "firefly_"
#define ST_DEVICE_NAME "tree"
#define ST_CONN_TIMEOUT 10000
#define ST_ANNOUNCE_PORT 3001
#define MDNS_DEBUG_RX TRUE
#define EEPROM_SIZE 512
#define BROADCAST_IP "225.0.0.1"
#define BROADCAST_PORT 3001
#define USE_WS TRUE
#define WS_PORT 1984
#define ST_SSID "thisisnotit"
#define ST_PWD  "Bl4k34Pr351d3nt"
